language: ruby
rvm:
  - 2.4.1

install: gem install jekyll
script: jekyll build

before_deploy:
  - pip install s3cmd
  - gem install jekyll

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
