language: ruby
rvm:
  - 2.4.1

install: gem install jekyll
script: jekyll build

before_deploy:
  - gem install jekyll
  - pip install -U six==1.11.0
  - pip install -U s3cmd==2.0.2

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
