# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kelley Robinson
email: hello@krobinson.me
description: > # this means to ignore newlines until "baseurl:"
  Software engineer, amateur chef. Likes automating, organizing, creating.
  Currently working with data and infrastructure at Sharethrough in San Francisco.
baseurl: "" # the subpath of your site, e.g. /blog
blogurl: "blog.krobinson.me"
url: "http://krobinson.me" # the base hostname & protocol for your site
twitter_username: kelleyrobinson
github_username:  robinske

# Build settings
markdown: kramdown
exclude: [deploy.sh, README.md]
