# Site settings
title: Kelley Robinson
email: hello@krobinson.me
description: >
  Engineer. Speaker. Feminist. Likes automating, organizing, cooking, creating. 
  @twilio dev evangelist. @umich alum
baseurl: "" 
blogurl: "blog.krobinson.me"
talksurl: "talks.krobinson.me"
url: "http://krobinson.me"
twitter_username: kelleyrobinson
github_username:  robinske

# Build settings
markdown: kramdown
exclude: [deploy.sh, README.md]
permalink: /posts/:title/
